environment:
  backend:
    DB_HOST: test-db-cluster.cluster-cpwwaa4iqa1s.us-east-2.rds.amazonaws.com
    EVM_CHAINS: anvil,anvil2
    EVM_NETWORK_URL_anvil: http://test-anvil.funkybit.fun:8545
    EVM_NETWORK_URL_anvil2: http://test-anvil2.funkybit.fun:8545
    AUTH_TOKEN_VALIDITY_INTERVAL: P1D
    SEQUENCER_HOST_NAME: test-sequencer.funkybit.fun
    SEQUENCER_PORT: "5337"
    JAVA_TOOL_OPTIONS: "-Xlog:gc+metaspace,gc+heap,gc:stdout:time,tags"
    ENABLE_TEST_ROUTES: "true"
    FAUCET_MODE: AllSymbols
    BITCOIN_NETWORK_ENABLED: "false"
  sequencer:
    QUEUE_HOME: "/data/queues/test"
    CHECKPOINTS_ENABLED: "false"
    SANDBOX_MODE: "true"
    STRICT_REPLAY_VALIDATION: "true"
    JAVA_TOOL_OPTIONS: "-Xlog:gc+metaspace,gc+heap,gc:stdout:time,tags"
  garp:
    QUEUE_HOME: "/data/queues/test"
    DB_HOST: test-db-cluster.cluster-cpwwaa4iqa1s.us-east-2.rds.amazonaws.com
    JAVA_TOOL_OPTIONS: "-Xlog:gc+metaspace,gc+heap,gc:stdout:time,tags"
  telegrambot:
    DB_HOST: test-db-cluster.cluster-cpwwaa4iqa1s.us-east-2.rds.amazonaws.com
    API_URL: http://test-api.funkybit.fun:9000
    EVM_CHAINS: anvil,anvil2
    EVM_NETWORK_URL_anvil: http://test-anvil.funkybit.fun:8545
    EVM_NETWORK_URL_anvil2: http://test-anvil2.funkybit.fun:8545
    FAUCET_SUPPORTED: "true"
  anvil2:
    CHAIN_ID: "31339"
  otterscan:
    ERIGON_URL: https://test-anvil.funkybit.fun
  otterscan2:
    ERIGON_URL: https://test-anvil2.funkybit.fun
services:
  api:
    image: 851725450525.dkr.ecr.us-east-2.amazonaws.com/backend
    count: 1
    is_essential: "true"
    environment: backend
    secrets:
      DB_CREDENTIALS: arn:aws:secretsmanager:us-east-2:851725450525:secret:rds!cluster-a00059f0-7cd7-4989-bd67-7af9e5899397-cWukH6
  ring:
    image: 851725450525.dkr.ecr.us-east-2.amazonaws.com/backend
    count: 1
    environment: backend
    secrets:
      DB_CREDENTIALS: arn:aws:secretsmanager:us-east-2:851725450525:secret:rds!cluster-a00059f0-7cd7-4989-bd67-7af9e5899397-cWukH6
  telegrambot:
    image: 851725450525.dkr.ecr.us-east-2.amazonaws.com/backend
    count: 1
    environment: telegrambot
    no_rolling_upgrade: "true"
    secrets:
      DB_CREDENTIALS: arn:aws:secretsmanager:us-east-2:851725450525:secret:rds!cluster-a00059f0-7cd7-4989-bd67-7af9e5899397-cWukH6
      TELEGRAM_BOT_TOKEN: arn:aws:secretsmanager:us-east-2:851725450525:secret:test/telegrambot/TELEGRAM_BOT_TOKEN-EJTdMA
  anvil:
    image: 851725450525.dkr.ecr.us-east-2.amazonaws.com/anvil
    count: 1
    is_essential: "true"
  otterscan:
    image: 851725450525.dkr.ecr.us-east-2.amazonaws.com/otterscan
    count: 1
    environment: otterscan
  anvil2:
    image: 851725450525.dkr.ecr.us-east-2.amazonaws.com/anvil
    count: 1
    is_essential: "true"
    environment: anvil2
  otterscan2:
    image: 851725450525.dkr.ecr.us-east-2.amazonaws.com/otterscan
    count: 1
    environment: otterscan2
  sequencer:
    image: 851725450525.dkr.ecr.us-east-2.amazonaws.com/sequencer
    count: 1
    is_essential: "true"
    no_rolling_upgrade: "true"
    environment: sequencer
  garp:
    image: 851725450525.dkr.ecr.us-east-2.amazonaws.com/sequencer
    count: 1
    is_essential: "true"
    no_rolling_upgrade: "true"
    environment: garp
    secrets:
      DB_CREDENTIALS: arn:aws:secretsmanager:us-east-2:851725450525:secret:rds!cluster-a00059f0-7cd7-4989-bd67-7af9e5899397-cWukH6

