# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gateway.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import order_pb2 as order__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgateway.proto\x12\tsequencer\x1a\x0border.proto2A\n\x07Gateway\x12\x36\n\x08\x41\x64\x64Order\x12\x10.sequencer.Order\x1a\x18.sequencer.OrderResponseB+\n\x19\x63o.chainring.apps.gatewayB\x0cGatewayProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gateway_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\031co.chainring.apps.gatewayB\014GatewayProtoP\001'
  _globals['_GATEWAY']._serialized_start=41
  _globals['_GATEWAY']._serialized_end=106
# @@protoc_insertion_point(module_scope)
