# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0border.proto\x12\tsequencer\"\xdc\x01\n\x05Order\x12\x0c\n\x04guid\x18\x01 \x01(\t\x12\x0e\n\x06market\x18\x02 \x01(\t\x12-\n\torderType\x18\x03 \x01(\x0e\x32\x1a.sequencer.Order.OrderType\x12\x0f\n\x07\x61\x64\x64ress\x18\x04 \x01(\t\x12\x0e\n\x06\x61mount\x18\x05 \x01(\t\x12\x12\n\x05price\x18\x06 \x01(\x01H\x00\x88\x01\x01\"G\n\tOrderType\x12\r\n\tMarketBuy\x10\x00\x12\x0e\n\nMarketSell\x10\x01\x12\x0c\n\x08LimitBuy\x10\x02\x12\r\n\tLimitSell\x10\x03\x42\x08\n\x06_price\"*\n\x06Orders\x12 \n\x06orders\x18\x01 \x03(\x0b\x32\x10.sequencer.Order\"\xf6\x01\n\rOrderResponse\x12\x0c\n\x04guid\x18\x01 \x01(\t\x12>\n\x0b\x64isposition\x18\x02 \x01(\x0e\x32).sequencer.OrderResponse.OrderDisposition\x12\x15\n\x08sequence\x18\x03 \x01(\x04H\x00\x88\x01\x01\x12\x16\n\x0eprocessingTime\x18\x04 \x01(\x04\"[\n\x10OrderDisposition\x12\n\n\x06\x46illed\x10\x00\x12\x13\n\x0fPartiallyFilled\x10\x01\x12\x0c\n\x08\x41\x63\x63\x65pted\x10\x02\x12\x0c\n\x08Rejected\x10\x03\x12\n\n\x06\x46\x61iled\x10\x04\x42\x0b\n\t_sequenceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ORDER']._serialized_start=27
  _globals['_ORDER']._serialized_end=247
  _globals['_ORDER_ORDERTYPE']._serialized_start=166
  _globals['_ORDER_ORDERTYPE']._serialized_end=237
  _globals['_ORDERS']._serialized_start=249
  _globals['_ORDERS']._serialized_end=291
  _globals['_ORDERRESPONSE']._serialized_start=294
  _globals['_ORDERRESPONSE']._serialized_end=540
  _globals['_ORDERRESPONSE_ORDERDISPOSITION']._serialized_start=436
  _globals['_ORDERRESPONSE_ORDERDISPOSITION']._serialized_end=527
# @@protoc_insertion_point(module_scope)
