name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# execute jobs sequentially per branch, needed to keep correct order of deployments
concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  build_push_backend:
    name: Build Backend and push to ECR
    permissions:
      id-token: write # needed for aws credentials
      contents: write
      checks: write # for writing test reports
    uses: ./.github/workflows/build-push-backend.yml

  build_frontend:
    name: Build web UI
    uses: ./.github/workflows/build-web-ui.yml

  build_telegram_mini_app:
    name: Build Telegram Mini App
    uses: ./.github/workflows/build-telegram-mini-app.yml

  stop_backend:
    name: Stop Backend
    if: ${{ github.event_name == 'push' }}
    needs: [ build_push_backend, build_frontend, build_telegram_mini_app ]
    permissions:
      id-token: write # needed for aws credentials
      contents: read
    uses: ./.github/workflows/deploy-backend.yml
    with:
      action: stop
      environment: test
      tag: ${{ needs.build_push_backend.outputs.docker_image_tag }}

  deprecate_contracts:
    name: Deprecate Contracts
    if: ${{ github.event_name == 'push' }}
    needs: [ stop_backend ]
    permissions:
      id-token: write # needed for aws credentials
      contents: read
    uses: ./.github/workflows/deprecate-contracts.yml
    secrets: inherit # needs access to secrets.CI_BASTION_KEY

  restart_anvil:
    name: Restart Anvil
    if: ${{ github.event_name == 'push' }}
    needs: [ deprecate_contracts ]
    permissions:
      id-token: write # needed for aws credentials
      contents: read
    uses: ./.github/workflows/restart-anvil.yml
    with:
      environment: test

  upgrade_backend:
    name: Deploy Backend
    if: ${{ github.event_name == 'push' }}
    needs: [ restart_anvil ]
    permissions:
      id-token: write # needed for aws credentials
      contents: read
    uses: ./.github/workflows/deploy-backend.yml
    with:
      action: upgrade
      environment: test
      tag: ${{ needs.build_push_backend.outputs.docker_image_tag }}

  start_backend:
    name: Stop Backend
    if: ${{ github.event_name == 'push' }}
    needs: [ upgrade_backend ]
    permissions:
      id-token: write # needed for aws credentials
      contents: read
    uses: ./.github/workflows/deploy-backend.yml
    with:
      action: start
      environment: test
      tag: ${{ needs.build_push_backend.outputs.docker_image_tag }}

  deploy_web_ui:
    name: Deploy Web UI
    if: ${{ github.event_name == 'push' }}
    needs: [ build_push_backend, build_frontend ]
    permissions:
      id-token: write # needed for aws credentials
      contents: read
    uses: ./.github/workflows/deploy-web-ui.yml
    with:
      environment: test

  deploy_telegram_mini_app:
    name: Deploy Telegram Mini App
    if: ${{ github.event_name == 'push' }}
    needs: [ build_push_backend, build_telegram_mini_app ]
    permissions:
      id-token: write # needed for aws credentials
      contents: read
    uses: ./.github/workflows/deploy-telegram-mini-app.yml
    with:
      environment: test

  integration_tests:
    name: Run integration tests
    needs: [ start_backend, deploy_web_ui, deploy_telegram_mini_app ]
    if: ${{ github.event_name == 'push' }}
    permissions:
      id-token: write # needed for aws credentials
      contents: read
      checks: write # for writing test reports
    uses: ./.github/workflows/integration-tests.yml
    secrets: inherit # needs access to secrets.CI_BASTION_KEY
