name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# execute jobs sequentially per branch, needed to keep correct order of deployments
concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  build_push_backend:
    name: Build Backend and push to ECR
    permissions:
      id-token: write # needed for aws credentials
      contents: write
      checks: write # for writing test reports
    uses: ./.github/workflows/build-push-backend.yml

  build_frontend:
    name: Build web UI
    uses: ./.github/workflows/build-web-ui.yml

  build_telegram_mini_app:
    name: Build Telegram Mini App
    uses: ./.github/workflows/build-telegram-mini-app.yml

  clear_database:
    name: Clear database
    if: ${{ github.event_name == 'push' }}
    needs: [ build_push_backend, build_frontend, build_telegram_mini_app ]
    permissions:
      id-token: write # needed for aws credentials
      contents: read
    uses: ./.github/workflows/clear-database.yml
    secrets: inherit # needs access to secrets.CI_BASTION_KEY

  upgrade_backend:
    name: Upgrade backend
    if: ${{ github.event_name == 'push' }}
    needs: [ clear_database ]
    permissions:
      id-token: write # needed for aws credentials
      contents: read
    uses: ./.github/workflows/upgrade-services.yml
    with:
      environment: test
      services: "ring,api,telegrambot,garp,sequencer"
      tag: ${{ needs.build_push_backend.outputs.docker_image_tag }}

  start_services:
    name: Start services
    if: ${{ github.event_name == 'push' }}
    needs: [ upgrade_backend ]
    permissions:
      id-token: write # needed for aws credentials
      contents: read
    uses: ./.github/workflows/start-services.yml
    with:
      environment: test
      services: "anvil,anvil2,ring,api,garp,sequencer,telegrambot,otterscan,otterscan2"

  deploy_web_ui:
    name: Deploy Web UI
    if: ${{ github.event_name == 'push' }}
    needs: [ start_services, build_frontend ]
    permissions:
      id-token: write # needed for aws credentials
      contents: read
    uses: ./.github/workflows/deploy-web-ui.yml
    with:
      environment: test

  deploy_telegram_mini_app:
    name: Deploy Telegram Mini App
    if: ${{ github.event_name == 'push' }}
    needs: [ start_services, build_telegram_mini_app ]
    permissions:
      id-token: write # needed for aws credentials
      contents: read
    uses: ./.github/workflows/deploy-telegram-mini-app.yml
    with:
      environment: test

  integration_tests:
    name: Run integration tests
    needs: [ start_services ]
    if: ${{ github.event_name == 'push' }}
    permissions:
      id-token: write # needed for aws credentials
      contents: read
      checks: write # for writing test reports
    uses: ./.github/workflows/integration-tests.yml
    secrets: inherit # needs access to secrets.CI_BASTION_KEY

  stop_services:
    name: Stop services
    if: ${{ github.event_name == 'push' && always() }} # always run this job, even if integration_tests job has failed or workflow cancelation was requested
    needs: [ integration_tests ]
    permissions:
      id-token: write # needed for aws credentials
      contents: read
    uses: ./.github/workflows/stop-services.yml
    with:
      environment: test
      services: "api,ring,telegrambot,garp,sequencer,anvil,otterscan,anvil2,otterscan2"

