name: Deploy Testnet

on:
  # Manual trigger from the UI
  workflow_dispatch:
    inputs:
      tag:
        description: 'Backend image tag'
        required: true
        type: string

# execute jobs sequentially per branch, needed to keep correct order of deployments
concurrency:
  group: deploy-testnet
  cancel-in-progress: false

jobs:
  deploy_backend:
    name: Deploy Backend
    permissions:
      id-token: write # needed for aws credentials
      contents: read
    uses: ./.github/workflows/deploy-backend.yml
    with:
      action: upgrade
      environment: testnet
      tag: ${{ inputs.tag }}

  deploy_web_ui:
    name: Deploy Web UI
    needs: [ deploy_backend ]
    permissions:
      id-token: write # needed for aws credentials
      contents: read
    uses: ./.github/workflows/deploy-web-ui.yml
    with:
      environment: testnet