name: Stop services

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment'
        required: true
        type: string
      services:
        description: 'Services'
        required: true
        type: string

# make sure it does not interfere with other jobs in progress
concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  stop-services:
    runs-on: ubuntu-latest
    permissions:
      # needed for aws credentials
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Setup AWS
        uses: ./.github/actions/setup-aws
      - name: Stop services
        run: |
          cd scripts
          test -d venv || python3 -m venv venv
          . ./venv/bin/activate && pip install --upgrade pip && pip install -r requirements.txt
          python3 ecs-deploy.py stop --env ${{ inputs.environment }} --services ${{ inputs.services }}
